#!/bin/sh
#/ Usage: bootstrap [bundle options]
#/
#/ Bundle install the dependencies.
#/
#/ Examples:
#/
#/   bootstrap
#/   bootstrap --local
#/

set -e
cd $(dirname "$0")/..

[ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ] && {
    grep '^#/' <"$0"| cut -c4-
    exit 0
}

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi
