#!/bin/sh
# Usage: script/pdfify /path/to/markdown/file.md
# creates octocat-friendly PDF from Markdown
#

# Exit immediately if a command exits with a non-zero status.
set -e

STYLE="style.css"
[ "$1" = "--student" -o "$1" = "-s" ] && {
    STYLE="student.css"
    shift
}

TMP=$( mktemp -d )
BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$(basename -s md "$1")"

pandoc "$1" \
    -f markdown_github \
    -t html5 \
    -B "${BASE_DIR}/.pdfify/header.html" \
    -o "${TMP}/${TARGET}html"

echo "${TMP}/${TARGET}html"

wkhtmltopdf \
    --page-size letter \
    --no-pdf-compression \
    --margin-top 15 \
    --margin-left 15 \
    --footer-left "$( date -u )" \
    --footer-right '[page]/[toPage]' \
    --footer-font-name 'Source Sans Pro' \
    --footer-line \
    --user-style-sheet "${BASE_DIR}/.pdfify/${STYLE}" \
    "${TMP}/${TARGET}html" "${TARGET}pdf"
